version: '3'
volumes:
  node_modules:
services:
  db:
    image: postgres
    ports:
     - "5433:5432"
    volumes: 
      - ../postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=fennel
      - POSTGRES_PASSWORD=fennel
      - POSTGRES_DB=fennel
  carddav:
    env_file:
      - .env
    build: 
      context: .
    ports:
     - "8888:8888"
    depends_on:
      - db
    volumes:
     - .:/fennel
     - node_modules:/fennel/node_modules
    image: fennel_valentino:latest_dev
